"on":
    push:
        branches:
            - main
name: Deploy to test-build-cache
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: exec porter apply
              env:
                PORTER_APP_NAME: test-build-cache
                PORTER_CLUSTER: "1"
                PORTER_DEPLOYMENT_TARGET_ID: 134cfeda-2b57-4b38-af6a-627ae2d23981
                PORTER_HOST: https://dgtown2.withporter.run
                PORTER_PR_NUMBER: ${{ github.event.number }}
                PORTER_PROJECT: "1"
                PORTER_REPO_NAME: ${{ github.event.repository.name }}
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_1_1 }}
                DOCKER_BUILDKIT: "1"
                PORTER_BUILDKIT_CACHE_TO_MODE: "max"
